/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import controller.GiaoDienChinhController;
import dao.MayTinhDAO;
import dao.SDMayDAO;
import daoImpl.MayTinhDAOImpl;
import daoImpl.SDMayDAOImpl;
import entity.Admin;
import entity.MayTinh;
import entity.SuDungMay;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import util.Style_Net;
import util.XAuth;

/**
 *
 * @author NITRO 5
 */
public class NetManagerJFrame extends javax.swing.JFrame implements GiaoDienChinhController {

    /**
     * Creates new form NetManagerJFrem w14 h410
     */
    int w = 220;
    int h = 690;
    private Timer dongHoTimer;
    MayTinhDAO dao = new MayTinhDAOImpl();

    public NetManagerJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        this.init();
    }

    void btnopmenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < w; i++) {
                    menuHeThong.setSize(i, h);
                    try {
                        Thread.sleep(2);
                    } catch (Exception e) {
                    }
                }
            }
        }).start();
    }

    void btnclmenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = w; i > 79; i--) {
                    menuHeThong.setSize(i, h);
                    try {
                        Thread.sleep(2);
                    } catch (Exception e) {
                    }
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuHeThong = new javax.swing.JPanel();
        btnQLNV = new javax.swing.JButton();
        btnQLTD = new javax.swing.JButton();
        btnQLMT = new javax.swing.JButton();
        btnQLTK = new javax.swing.JButton();
        lbclmenu = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNgayHienTai = new javax.swing.JLabel();
        pnlMenuTop = new javax.swing.JPanel();
        lblSoMayTrong = new javax.swing.JLabel();
        lblSoMayHoatDong = new javax.swing.JLabel();
        btnMoMay = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnTrandPass = new javax.swing.JButton();
        lblGioHienTai = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();
        lblBackRound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuHeThong.setBackground(new java.awt.Color(0, 0, 0, 50));
        menuHeThong.setForeground(new java.awt.Color(0, 0, 0, 120)
        );
        menuHeThong.setPreferredSize(new java.awt.Dimension(140, 410));
        menuHeThong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHeThongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuHeThongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuHeThongMouseExited(evt);
            }
        });

        btnQLNV.setBorder(null);
        btnQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNVActionPerformed(evt);
            }
        });

        btnQLTD.setBorder(null);
        btnQLTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTDActionPerformed(evt);
            }
        });

        btnQLMT.setBorder(null);
        btnQLMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLMTActionPerformed(evt);
            }
        });

        btnQLTK.setBorder(null);
        btnQLTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTKActionPerformed(evt);
            }
        });

        lbclmenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbclmenu.setText("X");
        lbclmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbclmenuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lý món ăn");

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quản lý nhân viên");

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quản lý máy tính");

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Thống kê");

        javax.swing.GroupLayout menuHeThongLayout = new javax.swing.GroupLayout(menuHeThong);
        menuHeThong.setLayout(menuHeThongLayout);
        menuHeThongLayout.setHorizontalGroup(
            menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(menuHeThongLayout.createSequentialGroup()
                .addGroup(menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuHeThongLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQLTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuHeThongLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQLTD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQLMT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuHeThongLayout.createSequentialGroup()
                        .addComponent(lbclmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2)))
        );

        menuHeThongLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnQLMT, btnQLNV, btnQLTD, btnQLTK});

        menuHeThongLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        menuHeThongLayout.setVerticalGroup(
            menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuHeThongLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuHeThongLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnQLMT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnQLTD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(menuHeThongLayout.createSequentialGroup()
                        .addComponent(lbclmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71)))
                .addGroup(menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuHeThongLayout.createSequentialGroup()
                        .addComponent(btnQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuHeThongLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(67, 67, 67)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        menuHeThongLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnQLMT, btnQLNV, btnQLTD, btnQLTK});

        menuHeThongLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        getContentPane().add(menuHeThong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 690));

        lblNgayHienTai.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        lblNgayHienTai.setForeground(new java.awt.Color(255, 255, 255));
        lblNgayHienTai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNgayHienTai.setText("Ngày hiện tại");
        getContentPane().add(lblNgayHienTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 620, 240, 60));

        pnlMenuTop.setBackground(new java.awt.Color(0, 0, 0, 50));
        pnlMenuTop.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlMenuTop.setForeground(new java.awt.Color(0, 0, 0, 0));
        pnlMenuTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuTopMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlMenuTopMouseReleased(evt);
            }
        });

        lblSoMayTrong.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblSoMayTrong.setForeground(new java.awt.Color(255, 255, 255));
        lblSoMayTrong.setText("Số máy trống");

        lblSoMayHoatDong.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblSoMayHoatDong.setForeground(new java.awt.Color(255, 255, 255));
        lblSoMayHoatDong.setText("Số máy hoạt động");

        btnMoMay.setBackground(new java.awt.Color(204, 204, 204));
        btnMoMay.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnMoMay.setText("Mở máy");
        btnMoMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoMayActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(204, 204, 204));
        btnLogOut.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 0, 0));
        btnLogOut.setText("Đăng xuất");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnTrandPass.setBackground(new java.awt.Color(204, 204, 204));
        btnTrandPass.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnTrandPass.setText("Đổi mật khẩu");
        btnTrandPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrandPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuTopLayout = new javax.swing.GroupLayout(pnlMenuTop);
        pnlMenuTop.setLayout(pnlMenuTopLayout);
        pnlMenuTopLayout.setHorizontalGroup(
            pnlMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuTopLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(lblSoMayTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSoMayHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(btnMoMay, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnTrandPass, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlMenuTopLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLogOut, btnMoMay});

        pnlMenuTopLayout.setVerticalGroup(
            pnlMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuTopLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoMay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoMayHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoMayTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrandPass, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        pnlMenuTopLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLogOut, btnMoMay, btnTrandPass});

        getContentPane().add(pnlMenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 90));

        lblGioHienTai.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        lblGioHienTai.setForeground(new java.awt.Color(255, 255, 255));
        lblGioHienTai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGioHienTai.setText("Giờ hiện tại");
        getContentPane().add(lblGioHienTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 570, 160, 60));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Tên");
        lblName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 140, 50));

        lblAnh.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh.setText("Ảnh người dùng");
        lblAnh.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(51, 51, 51)));
        jPanel2.add(lblAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 350));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 170, 230, 350));

        lblBackRound.setOpaque(true);
        lblBackRound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackRoundMouseEntered(evt);
            }
        });
        getContentPane().add(lblBackRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoMayActionPerformed
        this.showMoMay(this);
        CapNhat();
    }//GEN-LAST:event_btnMoMayActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        dangXuat();
        CapNhat();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        NgayHienTai();
    }//GEN-LAST:event_formWindowOpened

    private void menuHeThongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHeThongMouseEntered
        CapNhat();
    }//GEN-LAST:event_menuHeThongMouseEntered

    private void btnTrandPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrandPassActionPerformed
        new DoiMatKhauJDialog(null, true).setVisible(true);
        CapNhat();
    }//GEN-LAST:event_btnTrandPassActionPerformed

    private void lbclmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbclmenuActionPerformed
        btnclmenu();
        CapNhat();
    }//GEN-LAST:event_lbclmenuActionPerformed

    private void btnQLTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTKActionPerformed
        this.showQLThongke(this);
        CapNhat();
    }//GEN-LAST:event_btnQLTKActionPerformed

    private void btnQLMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLMTActionPerformed
        this.showQLmay(this);
        CapNhat();
    }//GEN-LAST:event_btnQLMTActionPerformed

    private void btnQLTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTDActionPerformed
        this.showQLOrder(this);
        CapNhat();
    }//GEN-LAST:event_btnQLTDActionPerformed

    private void btnQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNVActionPerformed
        this.showNhanVien(this);
        CapNhat();
    }//GEN-LAST:event_btnQLNVActionPerformed

    private void menuHeThongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHeThongMouseClicked
        btnopmenu();
        CapNhat();
    }//GEN-LAST:event_menuHeThongMouseClicked

    private void pnlMenuTopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuTopMouseReleased

    }//GEN-LAST:event_pnlMenuTopMouseReleased

    private void menuHeThongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHeThongMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHeThongMouseExited

    private void lblBackRoundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackRoundMouseEntered
        CapNhat();
    }//GEN-LAST:event_lblBackRoundMouseEntered

    private void pnlMenuTopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuTopMouseEntered
        CapNhat();
    }//GEN-LAST:event_pnlMenuTopMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Set FlatLaf (light theme)
            Style_Net.setup();
        } catch (Exception ex) {
            System.err.println("Không thể khởi tạo FlatLaf: " + ex.getMessage());
        }
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NetManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NetManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NetManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NetManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NetManagerJFrame().setVisible(true);
            }
        });

    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon myImage = new ImageIcon(ImagePath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), Image.SCALE_SMOOTH);
        return new ImageIcon(newImg);
    }

    public void setIconAll() {
        lblBackRound.setIcon(new ImageIcon("src/main/java/img/backgroundJFrame.png"));
        lblSoMayTrong.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icon-computer32x32.png"));
        lblSoMayHoatDong.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icon-computer32x32.png"));
        btnMoMay.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icon-Open32x32.png"));
        btnTrandPass.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icon-pass32x32.png"));
        btnLogOut.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icon-Out32x32.png"));
        btnQLNV.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icon-manager.png"));
        btnQLMT.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icocn-computer.png"));
        btnQLTD.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icon-food.png"));
        btnQLTK.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icocn-thongKe.png"));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMoMay;
    private javax.swing.JButton btnQLMT;
    private javax.swing.JButton btnQLNV;
    private javax.swing.JButton btnQLTD;
    private javax.swing.JButton btnQLTK;
    private javax.swing.JButton btnTrandPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton lbclmenu;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblBackRound;
    private javax.swing.JLabel lblGioHienTai;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNgayHienTai;
    private javax.swing.JLabel lblSoMayHoatDong;
    private javax.swing.JLabel lblSoMayTrong;
    private javax.swing.JPanel menuHeThong;
    private javax.swing.JPanel pnlMenuTop;
    // End of variables declaration

    // Modern Dashboard Components
    private JLabel lblDashboardTitle;
    private JLabel lblDongHoTop;
    private JLabel lblKpiRevenueVal;
    private JLabel lblKpiHoursVal;
    private JLabel lblKpiActiveVal;
    private JLabel lblKpiActiveSub;
    private JLabel lblKpiFoodVal;
    private JTable tblDashboardActive;
    private DefaultTableModel modelDashboardActive;
    private JLabel lblSidebarUserName;
    private JLabel lblSidebarUserRole;
    private JButton btnNavMoMay;
    private JButton btnNavThucDon;
    private JButton btnNavMayTinh;
    private JButton btnNavNhanVien;
    private JButton btnNavThongKe;
    private SDMayDAO sdMayDao = new SDMayDAOImpl();

    private void initNavyFrameTheme() {
        buildModernDashboard();
    }

    private void buildModernDashboard() {
        setTitle("NET-MANAGER - Hệ Thống Điều Hành Phòng Máy");
        setSize(1360, 780);
        setLocationRelativeTo(null);
        getContentPane().removeAll();
        getContentPane().setLayout(new BorderLayout());

        // 1. SIDEBAR (WEST) - Fixed width 230px, White background, border right
        JPanel pnlSidebar = new JPanel(new BorderLayout());
        pnlSidebar.setPreferredSize(new Dimension(230, 0));
        pnlSidebar.setBackground(Color.WHITE);
        pnlSidebar.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 1, Style_Net.BORDER_HAIRLINE));

        // Top brand & nav buttons
        JPanel pnlSidebarTop = new JPanel();
        pnlSidebarTop.setLayout(new BoxLayout(pnlSidebarTop, BoxLayout.Y_AXIS));
        pnlSidebarTop.setBackground(Color.WHITE);
        pnlSidebarTop.setBorder(new EmptyBorder(24, 16, 20, 16));

        JLabel lblBrand = new JLabel("NET-MANAGER");
        lblBrand.setFont(Style_Net.FONT_BRAND);
        lblBrand.setForeground(Style_Net.NAVY_PRIMARY);
        lblBrand.setAlignmentX(Component.LEFT_ALIGNMENT);
        lblBrand.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icon-computer32x32.png"));
        lblBrand.setIconTextGap(8);
        pnlSidebarTop.add(lblBrand);

        JLabel lblBrandSub = new JLabel("HỆ THỐNG ĐIỀU HÀNH");
        lblBrandSub.setFont(new Font("Segoe UI", Font.BOLD, 10));
        lblBrandSub.setForeground(Style_Net.TEXT_MUTED);
        lblBrandSub.setAlignmentX(Component.LEFT_ALIGNMENT);
        lblBrandSub.setBorder(new EmptyBorder(3, 40, 16, 0));
        pnlSidebarTop.add(lblBrandSub);

        // Nav buttons (Clean typography, no broken emoji glyphs)
        btnNavMoMay = createNavButton("Sơ đồ máy trạm", true);
        btnNavMayTinh = createNavButton("Quản lý máy tính", false);
        btnNavThucDon = createNavButton("Quản lý thực đơn", false);
        btnNavNhanVien = createNavButton("Quản lý nhân viên", false);
        btnNavThongKe = createNavButton("Thống kê doanh thu", false);

        btnNavMoMay.addActionListener(e -> { showMoMay(this); CapNhat(); });
        btnNavMayTinh.addActionListener(e -> { showQLmay(this); CapNhat(); });
        btnNavThucDon.addActionListener(e -> { showQLOrder(this); CapNhat(); });
        btnNavNhanVien.addActionListener(e -> { showNhanVien(this); CapNhat(); });
        btnNavThongKe.addActionListener(e -> { showQLThongke(this); CapNhat(); });

        pnlSidebarTop.add(btnNavMoMay);
        pnlSidebarTop.add(Box.createVerticalStrut(6));
        pnlSidebarTop.add(btnNavMayTinh);
        pnlSidebarTop.add(Box.createVerticalStrut(6));
        pnlSidebarTop.add(btnNavThucDon);
        pnlSidebarTop.add(Box.createVerticalStrut(6));
        pnlSidebarTop.add(btnNavNhanVien);
        pnlSidebarTop.add(Box.createVerticalStrut(6));
        pnlSidebarTop.add(btnNavThongKe);

        pnlSidebar.add(pnlSidebarTop, BorderLayout.NORTH);

        // Bottom User Card
        JPanel pnlUserBottom = new JPanel(new BorderLayout(8, 0));
        pnlUserBottom.setBackground(Color.WHITE);
        pnlUserBottom.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createMatteBorder(1, 0, 0, 0, Style_Net.BORDER_HAIRLINE),
            new EmptyBorder(14, 16, 16, 16)
        ));

        JPanel pnlUserText = new JPanel();
        pnlUserText.setLayout(new BoxLayout(pnlUserText, BoxLayout.Y_AXIS));
        pnlUserText.setBackground(Color.WHITE);

        lblSidebarUserName = new JLabel(XAuth.user != null ? XAuth.user.getTen() : "admin");
        lblSidebarUserName.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblSidebarUserName.setForeground(Style_Net.NAVY_PRIMARY);

        lblSidebarUserRole = new JLabel(XAuth.user != null && XAuth.user.getVaiTro() == 1 ? "Quản trị viên ca trực" : "Nhân viên ca trực");
        lblSidebarUserRole.setFont(new Font("Segoe UI", Font.PLAIN, 11));
        lblSidebarUserRole.setForeground(Style_Net.TEXT_MUTED);

        pnlUserText.add(lblSidebarUserName);
        pnlUserText.add(lblSidebarUserRole);

        JButton btnLogout = new JButton("Đăng xuất");
        btnLogout.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btnLogout.setForeground(Style_Net.COLOR_DANGER);
        btnLogout.setBackground(Color.WHITE);
        btnLogout.setBorder(null);
        btnLogout.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnLogout.setContentAreaFilled(false);
        btnLogout.addActionListener(e -> dangXuat());

        pnlUserBottom.add(pnlUserText, BorderLayout.WEST);
        pnlUserBottom.add(btnLogout, BorderLayout.EAST);
        pnlSidebar.add(pnlUserBottom, BorderLayout.SOUTH);

        getContentPane().add(pnlSidebar, BorderLayout.WEST);

        // 2. MAIN DASHBOARD (CENTER)
        JPanel pnlDashboard = new JPanel(new BorderLayout(0, 18));
        pnlDashboard.setBackground(Style_Net.BG_CANVAS);
        pnlDashboard.setBorder(new EmptyBorder(22, 28, 22, 28));

        // Top bar
        JPanel pnlTopBar = new JPanel(new BorderLayout());
        pnlTopBar.setOpaque(false);

        lblDashboardTitle = new JLabel("TỔNG QUAN VẬN HÀNH PHÒNG MÁY");
        lblDashboardTitle.setFont(new Font("Segoe UI", Font.BOLD, 22));
        lblDashboardTitle.setForeground(Style_Net.NAVY_PRIMARY);

        lblDongHoTop = new JLabel("Đang tải thời gian...");
        lblDongHoTop.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        lblDongHoTop.setForeground(Style_Net.TEXT_MUTED);

        pnlTopBar.add(lblDashboardTitle, BorderLayout.WEST);
        pnlTopBar.add(lblDongHoTop, BorderLayout.EAST);
        pnlDashboard.add(pnlTopBar, BorderLayout.NORTH);

        // Center content area
        JPanel pnlCenterBody = new JPanel(new BorderLayout(0, 18));
        pnlCenterBody.setOpaque(false);

        // KPI Cards Row
        JPanel pnlKPIContainer = new JPanel(new GridLayout(1, 4, 16, 0));
        pnlKPIContainer.setOpaque(false);
        pnlKPIContainer.setPreferredSize(new Dimension(0, 95));

        // KPI 1: Doanh thu hôm nay
        JPanel kpi1 = Style_Net.createCardPanel();
        kpi1.setLayout(new BoxLayout(kpi1, BoxLayout.Y_AXIS));
        JLabel t1 = new JLabel("DOANH THU HÔM NAY"); t1.setFont(new Font("Segoe UI", Font.BOLD, 11)); t1.setForeground(Style_Net.TEXT_MUTED);
        lblKpiRevenueVal = new JLabel("1.845.000 ₫"); lblKpiRevenueVal.setFont(new Font("Segoe UI", Font.BOLD, 22)); lblKpiRevenueVal.setForeground(Style_Net.NAVY_PRIMARY);
        JLabel s1 = new JLabel("↑ 12% so với hôm qua"); s1.setFont(new Font("Segoe UI", Font.PLAIN, 12)); s1.setForeground(Style_Net.COLOR_SUCCESS);
        kpi1.add(t1); kpi1.add(Box.createVerticalStrut(3)); kpi1.add(lblKpiRevenueVal); kpi1.add(Box.createVerticalStrut(3)); kpi1.add(s1);

        // KPI 2: Tổng giờ chơi
        JPanel kpi2 = Style_Net.createCardPanel();
        kpi2.setLayout(new BoxLayout(kpi2, BoxLayout.Y_AXIS));
        JLabel t2 = new JLabel("TỔNG GIỜ CHƠI GHI NHẬN"); t2.setFont(new Font("Segoe UI", Font.BOLD, 11)); t2.setForeground(Style_Net.TEXT_MUTED);
        lblKpiHoursVal = new JLabel("38.5 giờ"); lblKpiHoursVal.setFont(new Font("Segoe UI", Font.BOLD, 22)); lblKpiHoursVal.setForeground(Style_Net.NAVY_PRIMARY);
        JLabel s2 = new JLabel("Bình quân 2.8h / máy"); s2.setFont(new Font("Segoe UI", Font.PLAIN, 12)); s2.setForeground(Style_Net.TEXT_MUTED);
        kpi2.add(t2); kpi2.add(Box.createVerticalStrut(3)); kpi2.add(lblKpiHoursVal); kpi2.add(Box.createVerticalStrut(3)); kpi2.add(s2);

        // KPI 3: Máy đang hoạt động
        JPanel kpi3 = Style_Net.createCardPanel();
        kpi3.setLayout(new BoxLayout(kpi3, BoxLayout.Y_AXIS));
        JLabel t3 = new JLabel("MÁY ĐANG HOẠT ĐỘNG"); t3.setFont(new Font("Segoe UI", Font.BOLD, 11)); t3.setForeground(Style_Net.TEXT_MUTED);
        lblKpiActiveVal = new JLabel("4 / 13 máy"); lblKpiActiveVal.setFont(new Font("Segoe UI", Font.BOLD, 22)); lblKpiActiveVal.setForeground(Style_Net.NAVY_PRIMARY);
        lblKpiActiveSub = new JLabel("Hiệu suất phòng: 31%"); lblKpiActiveSub.setFont(new Font("Segoe UI", Font.PLAIN, 12)); lblKpiActiveSub.setForeground(Style_Net.NAVY_ACCENT);
        kpi3.add(t3); kpi3.add(Box.createVerticalStrut(3)); kpi3.add(lblKpiActiveVal); kpi3.add(Box.createVerticalStrut(3)); kpi3.add(lblKpiActiveSub);

        // KPI 4: Món bán chạy nhất
        JPanel kpi4 = Style_Net.createCardPanel();
        kpi4.setLayout(new BoxLayout(kpi4, BoxLayout.Y_AXIS));
        JLabel t4 = new JLabel("MÓN BÁN CHẠY NHẤT"); t4.setFont(new Font("Segoe UI", Font.BOLD, 11)); t4.setForeground(Style_Net.TEXT_MUTED);
        lblKpiFoodVal = new JLabel("Sting đỏ ướp lạnh"); lblKpiFoodVal.setFont(new Font("Segoe UI", Font.BOLD, 20)); lblKpiFoodVal.setForeground(Style_Net.NAVY_PRIMARY);
        JLabel s4 = new JLabel("18 lon đã bán hôm nay"); s4.setFont(new Font("Segoe UI", Font.PLAIN, 12)); s4.setForeground(Style_Net.TEXT_MUTED);
        kpi4.add(t4); kpi4.add(Box.createVerticalStrut(3)); kpi4.add(lblKpiFoodVal); kpi4.add(Box.createVerticalStrut(3)); kpi4.add(s4);

        pnlKPIContainer.add(kpi1);
        pnlKPIContainer.add(kpi2);
        pnlKPIContainer.add(kpi3);
        pnlKPIContainer.add(kpi4);

        pnlCenterBody.add(pnlKPIContainer, BorderLayout.NORTH);

        // Split Content Area (Left: Active Sessions Table ~65%, Right: Notices ~35%)
        JPanel pnlSplit = new JPanel(new BorderLayout(18, 0));
        pnlSplit.setOpaque(false);

        // Left: Active Machines Card
        JPanel pnlLeftCard = Style_Net.createCardPanel();
        pnlLeftCard.setLayout(new BorderLayout(0, 12));

        JPanel pnlLeftHeader = new JPanel(new BorderLayout());
        pnlLeftHeader.setOpaque(false);
        JLabel lblActiveTitle = new JLabel("CÁC MÁY ĐANG CÓ KHÁCH CHƠI");
        lblActiveTitle.setFont(Style_Net.FONT_HEADER);
        lblActiveTitle.setForeground(Style_Net.NAVY_PRIMARY);
        JLabel lblActiveRealtime = new JLabel("Cập nhật thời gian thực");
        lblActiveRealtime.setFont(Style_Net.FONT_SMALL);
        lblActiveRealtime.setForeground(Style_Net.TEXT_MUTED);
        pnlLeftHeader.add(lblActiveTitle, BorderLayout.WEST);
        pnlLeftHeader.add(lblActiveRealtime, BorderLayout.EAST);
        pnlLeftCard.add(pnlLeftHeader, BorderLayout.NORTH);

        String[] cols = {"MÁY TRẠM", "GIỜ MỞ", "THỜI GIAN CHƠI", "ĐƠN GIÁ", "TẠM TÍNH", "THAO TÁC"};
        modelDashboardActive = new DefaultTableModel(cols, 0) {
            @Override
            public boolean isCellEditable(int row, int col) { return col == 5; }
        };
        tblDashboardActive = new JTable(modelDashboardActive);
        Style_Net.styleTable(tblDashboardActive);
        tblDashboardActive.setRowHeight(40);

        DefaultTableCellRenderer activeCellRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable tbl, Object val, boolean isSel, boolean hasFoc, int row, int col) {
                if (col == 0) {
                    JPanel p = new JPanel(new FlowLayout(FlowLayout.LEFT, 6, 8));
                    p.setOpaque(true);
                    p.setBackground(isSel ? tbl.getSelectionBackground() : (row % 2 == 0 ? Color.WHITE : new Color(0xF8, 0xFA, 0xFC)));
                    JLabel name = new JLabel(String.valueOf(val));
                    name.setFont(new Font("Segoe UI", Font.BOLD, 13));
                    name.setForeground(isSel ? Color.WHITE : Style_Net.NAVY_PRIMARY);
                    JLabel badge = Style_Net.createBadge("ĐANG CHƠI", "blue");
                    p.add(name);
                    p.add(badge);
                    return p;
                } else if (col == 2) {
                    JLabel lbl = (JLabel) super.getTableCellRendererComponent(tbl, val, isSel, hasFoc, row, col);
                    lbl.setFont(new Font("Segoe UI", Font.BOLD, 13));
                    lbl.setForeground(isSel ? Color.WHITE : Style_Net.NAVY_ACCENT);
                    return lbl;
                } else if (col == 4) {
                    JLabel lbl = (JLabel) super.getTableCellRendererComponent(tbl, val, isSel, hasFoc, row, col);
                    lbl.setFont(new Font("Segoe UI", Font.BOLD, 13));
                    lbl.setForeground(isSel ? Color.WHITE : Style_Net.NAVY_PRIMARY);
                    return lbl;
                } else if (col == 5) {
                    JButton btn = new JButton("Xem máy");
                    Style_Net.styleSecondaryButton(btn);
                    btn.setFont(new Font("Segoe UI", Font.BOLD, 12));
                    return btn;
                }
                return super.getTableCellRendererComponent(tbl, val, isSel, hasFoc, row, col);
            }
        };
        for (int i = 0; i < 6; i++) {
            tblDashboardActive.getColumnModel().getColumn(i).setCellRenderer(activeCellRenderer);
        }

        tblDashboardActive.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2 || tblDashboardActive.getSelectedColumn() == 5) {
                    showMoMay(NetManagerJFrame.this);
                    CapNhat();
                }
            }
        });

        JScrollPane scrollActive = new JScrollPane(tblDashboardActive);
        scrollActive.setBorder(new LineBorder(Style_Net.BORDER_HAIRLINE, 1));
        pnlLeftCard.add(scrollActive, BorderLayout.CENTER);
        pnlSplit.add(pnlLeftCard, BorderLayout.CENTER);

        // Right: Operational Notices Card
        JPanel pnlRightNotices = Style_Net.createCardPanel();
        pnlRightNotices.setPreferredSize(new Dimension(320, 0));
        pnlRightNotices.setLayout(new BoxLayout(pnlRightNotices, BoxLayout.Y_AXIS));

        JLabel lblNoticesTitle = new JLabel("THÔNG BÁO VẬN HÀNH");
        lblNoticesTitle.setFont(Style_Net.FONT_HEADER);
        lblNoticesTitle.setForeground(Style_Net.NAVY_PRIMARY);
        lblNoticesTitle.setAlignmentX(Component.LEFT_ALIGNMENT);
        pnlRightNotices.add(lblNoticesTitle);
        pnlRightNotices.add(Box.createVerticalStrut(14));

        pnlRightNotices.add(createNoticeBox(
            "Máy 13 đang bảo trì",
            "Lý do: Hỏng phím cơ. Đã thông báo bộ phận kỹ thuật kiểm tra.",
            new Color(0xD9, 0x77, 0x06),
            new Color(0xFF, 0xFB, 0xEB)
        ));
        pnlRightNotices.add(Box.createVerticalStrut(10));

        pnlRightNotices.add(createNoticeBox(
            "Kho thực đơn F&B ổn định",
            "Sting đỏ còn 50 lon, Mì tôm trứng còn 50 phần. Đủ phục vụ ca tối.",
            Style_Net.NAVY_ACCENT,
            new Color(0xEF, 0xF6, 0xFF)
        ));
        pnlRightNotices.add(Box.createVerticalStrut(10));

        String cashier = (XAuth.user != null) ? XAuth.user.getTen() : "admin";
        pnlRightNotices.add(createNoticeBox(
            "Ca trực hiện tại",
            "Thu ngân phụ trách: " + cashier + " (Bàn giao ca lúc 23:00).",
            Style_Net.COLOR_SUCCESS,
            new Color(0xF0, 0xFD, 0xF4)
        ));
        pnlRightNotices.add(Box.createGlue());

        pnlSplit.add(pnlRightNotices, BorderLayout.EAST);
        pnlCenterBody.add(pnlSplit, BorderLayout.CENTER);

        pnlDashboard.add(pnlCenterBody, BorderLayout.CENTER);
        getContentPane().add(pnlDashboard, BorderLayout.CENTER);

        getContentPane().revalidate();
        getContentPane().repaint();
    }

    private JButton createNavButton(String text, boolean active) {
        JButton btn = new JButton(text);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 13));
        btn.setHorizontalAlignment(SwingConstants.LEFT);
        btn.setMaximumSize(new Dimension(Integer.MAX_VALUE, 44));
        btn.setPreferredSize(new Dimension(194, 44));
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn.setFocusPainted(false);
        if (active) {
            btn.setBackground(Style_Net.NAVY_PRIMARY);
            btn.setForeground(Color.WHITE);
            btn.setBorder(BorderFactory.createCompoundBorder(
                new LineBorder(Style_Net.NAVY_PRIMARY, 1, true),
                new EmptyBorder(8, 14, 8, 14)
            ));
        } else {
            btn.setBackground(Color.WHITE);
            btn.setForeground(Style_Net.NAVY_PRIMARY);
            btn.setBorder(BorderFactory.createCompoundBorder(
                new LineBorder(Color.WHITE, 1, true),
                new EmptyBorder(8, 14, 8, 14)
            ));
            btn.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(0xF1, 0xF5, 0xF9));
                }
                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(Color.WHITE);
                }
            });
        }
        return btn;
    }

    private JPanel createNoticeBox(String title, String desc, Color accentColor, Color bg) {
        JPanel box = new JPanel(new BorderLayout(0, 4));
        box.setBackground(Color.WHITE);
        box.setMaximumSize(new Dimension(Integer.MAX_VALUE, 80));
        box.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createMatteBorder(0, 4, 0, 0, accentColor),
            BorderFactory.createCompoundBorder(
                new LineBorder(Style_Net.BORDER_HAIRLINE, 1),
                new EmptyBorder(10, 12, 10, 12)
            )
        ));

        JLabel lblTitle = new JLabel(title);
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lblTitle.setForeground(accentColor);

        JLabel lblDesc = new JLabel("<html><body style='width: 250px;'>" + desc + "</body></html>");
        lblDesc.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        lblDesc.setForeground(Style_Net.TEXT_MUTED);

        box.add(lblTitle, BorderLayout.NORTH);
        box.add(lblDesc, BorderLayout.CENTER);
        return box;
    }

    public void refreshDashboardData() {
        int soMayHD = dao.getSoMayDangHoatDong();
        int soMayTrong = dao.getSoMayDangTrong();
        int tongMay = soMayHD + soMayTrong;
        if (tongMay == 0) tongMay = 13;
        int pct = (int) Math.round((double) soMayHD * 100.0 / tongMay);

        if (lblKpiActiveVal != null) {
            lblKpiActiveVal.setText(soMayHD + " / " + tongMay + " máy");
        }
        if (lblKpiActiveSub != null) {
            lblKpiActiveSub.setText("Hiệu suất phòng: " + pct + "%");
        }

        if (modelDashboardActive != null) {
            modelDashboardActive.setRowCount(0);
            List<SuDungMay> list = sdMayDao.findAll();
            for (SuDungMay s : list) {
                if ("Hoạt động".equalsIgnoreCase(s.getTrangThai()) || "Chưa thanh toán".equalsIgnoreCase(s.getTrangThai())) {
                    String tenMay = s.getTenMay();
                    String gioMo = (s.getGioBatDau() != null) ? s.getGioBatDau().toString() : "--:--:--";
                    float rate = s.getGiaTheoGio();

                    long elapsed = 0;
                    if (s.getGioBatDau() != null) {
                        try {
                            java.time.LocalDate pDate = (s.getNgayChoi() != null) ? s.getNgayChoi().toLocalDate() : java.time.LocalDate.now();
                            java.time.LocalTime sTime = s.getGioBatDau().toLocalTime();
                            java.time.LocalDateTime sDt = java.time.LocalDateTime.of(pDate, sTime);
                            elapsed = Math.max(0, java.time.Duration.between(sDt, java.time.LocalDateTime.now()).getSeconds());
                        } catch (Exception ignored) {}
                    }
                    long h = elapsed / 3600;
                    long m = (elapsed % 3600) / 60;
                    String thoiGian = (h > 0) ? String.format("%02dh %02dm", h, m) : String.format("%02dm", m);
                    long minutes = elapsed / 60;
                    if ((elapsed % 60) >= 30) minutes++;
                    if (minutes == 0 && elapsed > 0) minutes = 1;
                    double hoursPlayed = Math.ceil((minutes / 60.0) * 100.0) / 100.0;
                    double tamTinh = Math.ceil((hoursPlayed * rate) * 100.0) / 100.0;

                    modelDashboardActive.addRow(new Object[]{
                        tenMay,
                        gioMo,
                        thoiGian,
                        Style_Net.formatMoney(rate) + "/h",
                        Style_Net.formatMoney(tamTinh),
                        "Xem máy"
                    });
                }
            }
        }
    }

    @Override
    public void init() {
        this.showWelcome(this);
        this.showLogin(this);
        initNavyFrameTheme();
        CapNhat();
        if (XAuth.user != null) {
            setRole();
        } else {
            dispose();
        }
        startDongHo();
    }

    private void loadAnhChinh(Admin admin) {
        if (lblAnh != null && admin.getAnh() != null && !admin.getAnh().isEmpty()) {
            String path = admin.getAnh();
            File f = new File(path);
            if (!f.exists()) {
                String alt = "src/images/" + path;
                if (new File(alt).exists()) {
                    path = alt;
                }
            }
            lblAnh.setIcon(ResizeImage(path));
        }
    }

    public void setRole() {
        if (XAuth.user == null) return;
        int role = XAuth.user.getVaiTro();
        String name = XAuth.user.getTen();

        if (lblSidebarUserName != null) lblSidebarUserName.setText(name);
        if (lblSidebarUserRole != null) {
            lblSidebarUserRole.setText(role == 1 ? "Quản trị viên ca trực" : "Nhân viên ca trực");
        }

        if (role == 2) { // Nhân viên
            if (btnNavNhanVien != null) btnNavNhanVien.setEnabled(false);
            if (btnNavMayTinh != null) btnNavMayTinh.setEnabled(false);
            if (btnNavThongKe != null) btnNavThongKe.setEnabled(false);
            if (btnNavThucDon != null) btnNavThucDon.setEnabled(false);
        } else {
            if (btnNavNhanVien != null) btnNavNhanVien.setEnabled(true);
            if (btnNavMayTinh != null) btnNavMayTinh.setEnabled(true);
            if (btnNavThongKe != null) btnNavThongKe.setEnabled(true);
            if (btnNavThucDon != null) btnNavThucDon.setEnabled(true);
        }
    }

    private void dangXuat() {
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn đăng xuất?", "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            XAuth.clear();
            this.setVisible(false);
            DangNhapJDialog dangNhap = new DangNhapJDialog(this, true);
            dangNhap.setVisible(true);
            if (XAuth.isLogin()) {
                this.setVisible(true);
                setRole();
                CapNhat();
            } else {
                dispose();
            }
        }
    }

    public void NgayHienTai() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String ngayHienTai = sdf.format(new Date());
        if (lblNgayHienTai != null) lblNgayHienTai.setText(ngayHienTai);
    }

    public void soMayHD() {
        int soMayHD = dao.getSoMayDangHoatDong();
        if (lblSoMayHoatDong != null) {
            lblSoMayHoatDong.setText("<html>"
                    + "<span style='color: #64748B; font-size: 12px; font-weight: 600;'>ĐANG HOẠT ĐỘNG: </span> "
                    + "<span style='color: #059669; font-size: 16px; font-weight: bold;'>" + soMayHD + " MÁY</span>"
                    + "</html>");
        }
    }

    public void soMayT() {
        int soMayTrong = dao.getSoMayDangTrong();
        if (lblSoMayTrong != null) {
            lblSoMayTrong.setText("<html>"
                    + "<span style='color: #64748B; font-size: 12px; font-weight: 600;'>MÁY TRỐNG: </span> "
                    + "<span style='color: #0F172A; font-size: 16px; font-weight: bold;'>" + soMayTrong + " MÁY</span>"
                    + "</html>");
        }
    }

    public void CapNhat() {
        soMayHD();
        soMayT();
        refreshDashboardData();
    }

    private void startDongHo() {
        dongHoTimer = new Timer(1000, e -> {
            SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd/MM/yyyy • HH:mm:ss", new java.util.Locale("vi", "VN"));
            String timeStr = sdf.format(new Date());
            if (lblDongHoTop != null) {
                lblDongHoTop.setText(timeStr);
            }
            if (lblGioHienTai != null) {
                lblGioHienTai.setText(timeStr);
            }
        });
        dongHoTimer.start();
    }

}
