/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import controller.GiaoDienChinhController;
import dao.MayTinhDAO;
import daoImpl.MayTinhDAOImpl;
import entity.Admin;
import java.awt.Image;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import util.Style_Net;
import util.XAuth;

/**
 *
 * @author NITRO 5
 */
public class NetManagerJFrame extends javax.swing.JFrame implements GiaoDienChinhController {

    /**
     * Creates new form NetManagerJFrem w14 h410
     */
    int w = 220;
    int h = 690;
    private Timer dongHoTimer;
    MayTinhDAO dao = new MayTinhDAOImpl();

    public NetManagerJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        this.init();
    }

    void btnopmenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < w; i++) {
                    menuHeThong.setSize(i, h);
                    try {
                        Thread.sleep(2);
                    } catch (Exception e) {
                    }
                }
            }
        }).start();
    }

    void btnclmenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = w; i > 79; i--) {
                    menuHeThong.setSize(i, h);
                    try {
                        Thread.sleep(2);
                    } catch (Exception e) {
                    }
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuHeThong = new javax.swing.JPanel();
        btnQLNV = new javax.swing.JButton();
        btnQLTD = new javax.swing.JButton();
        btnQLMT = new javax.swing.JButton();
        btnQLTK = new javax.swing.JButton();
        lbclmenu = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNgayHienTai = new javax.swing.JLabel();
        pnlMenuTop = new javax.swing.JPanel();
        lblSoMayTrong = new javax.swing.JLabel();
        lblSoMayHoatDong = new javax.swing.JLabel();
        btnMoMay = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnTrandPass = new javax.swing.JButton();
        lblGioHienTai = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();
        lblBackRound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuHeThong.setBackground(new java.awt.Color(0, 0, 0, 50));
        menuHeThong.setForeground(new java.awt.Color(0, 0, 0, 120)
        );
        menuHeThong.setPreferredSize(new java.awt.Dimension(140, 410));
        menuHeThong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHeThongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuHeThongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuHeThongMouseExited(evt);
            }
        });

        btnQLNV.setIcon(new javax.swing.ImageIcon("C:\\Users\\NITRO 5\\Documents\\NetBeansProjects\\NET-MANAGERTest\\NET-MANAGER-main\\src\\main\\java\\img\\Ui-manager-icon-manager.png")); // NOI18N
        btnQLNV.setBorder(null);
        btnQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNVActionPerformed(evt);
            }
        });

        btnQLTD.setIcon(new javax.swing.ImageIcon("C:\\Users\\NITRO 5\\Documents\\NetBeansProjects\\NET-MANAGER\\NET-MANAGER-main\\src\\main\\java\\img\\Ui-manager-icon-food.png")); // NOI18N
        btnQLTD.setBorder(null);
        btnQLTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTDActionPerformed(evt);
            }
        });

        btnQLMT.setIcon(new javax.swing.ImageIcon("C:\\Users\\NITRO 5\\Documents\\NetBeansProjects\\NET-MANAGER\\NET-MANAGER-main\\src\\main\\java\\img\\Ui-manager-icocn-computer.png")); // NOI18N
        btnQLMT.setBorder(null);
        btnQLMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLMTActionPerformed(evt);
            }
        });

        btnQLTK.setIcon(new javax.swing.ImageIcon("C:\\Users\\NITRO 5\\Documents\\NetBeansProjects\\NET-MANAGERTest\\NET-MANAGER-main\\src\\main\\java\\img\\Ui-manager-icocn-thongKe.png")); // NOI18N
        btnQLTK.setBorder(null);
        btnQLTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTKActionPerformed(evt);
            }
        });

        lbclmenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbclmenu.setText("X");
        lbclmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbclmenuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lý món ăn");

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quản lý nhân viên");

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quản lý máy tính");

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Thống kê");

        javax.swing.GroupLayout menuHeThongLayout = new javax.swing.GroupLayout(menuHeThong);
        menuHeThong.setLayout(menuHeThongLayout);
        menuHeThongLayout.setHorizontalGroup(
            menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(menuHeThongLayout.createSequentialGroup()
                .addGroup(menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuHeThongLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQLTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuHeThongLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQLTD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQLMT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuHeThongLayout.createSequentialGroup()
                        .addComponent(lbclmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2)))
        );

        menuHeThongLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnQLMT, btnQLNV, btnQLTD, btnQLTK});

        menuHeThongLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        menuHeThongLayout.setVerticalGroup(
            menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuHeThongLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuHeThongLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnQLMT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnQLTD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(menuHeThongLayout.createSequentialGroup()
                        .addComponent(lbclmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71)))
                .addGroup(menuHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuHeThongLayout.createSequentialGroup()
                        .addComponent(btnQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuHeThongLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(67, 67, 67)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        menuHeThongLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnQLMT, btnQLNV, btnQLTD, btnQLTK});

        menuHeThongLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        getContentPane().add(menuHeThong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 690));

        lblNgayHienTai.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        lblNgayHienTai.setForeground(new java.awt.Color(255, 255, 255));
        lblNgayHienTai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNgayHienTai.setText("Ngày hiện tại");
        getContentPane().add(lblNgayHienTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 620, 240, 60));

        pnlMenuTop.setBackground(new java.awt.Color(0, 0, 0, 50));
        pnlMenuTop.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlMenuTop.setForeground(new java.awt.Color(0, 0, 0, 0));
        pnlMenuTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuTopMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlMenuTopMouseReleased(evt);
            }
        });

        lblSoMayTrong.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblSoMayTrong.setForeground(new java.awt.Color(255, 255, 255));
        lblSoMayTrong.setText("Số máy trống");

        lblSoMayHoatDong.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblSoMayHoatDong.setForeground(new java.awt.Color(255, 255, 255));
        lblSoMayHoatDong.setText("Số máy hoạt động");

        btnMoMay.setBackground(new java.awt.Color(204, 204, 204));
        btnMoMay.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnMoMay.setText("Mở máy");
        btnMoMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoMayActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(204, 204, 204));
        btnLogOut.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 0, 0));
        btnLogOut.setText("Đăng xuất");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnTrandPass.setBackground(new java.awt.Color(204, 204, 204));
        btnTrandPass.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnTrandPass.setText("Đổi mật khẩu");
        btnTrandPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrandPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuTopLayout = new javax.swing.GroupLayout(pnlMenuTop);
        pnlMenuTop.setLayout(pnlMenuTopLayout);
        pnlMenuTopLayout.setHorizontalGroup(
            pnlMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuTopLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(lblSoMayTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSoMayHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(btnMoMay, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnTrandPass, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlMenuTopLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLogOut, btnMoMay});

        pnlMenuTopLayout.setVerticalGroup(
            pnlMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuTopLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoMay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoMayHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoMayTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrandPass, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        pnlMenuTopLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLogOut, btnMoMay, btnTrandPass});

        getContentPane().add(pnlMenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 90));

        lblGioHienTai.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        lblGioHienTai.setForeground(new java.awt.Color(255, 255, 255));
        lblGioHienTai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGioHienTai.setText("Giờ hiện tại");
        getContentPane().add(lblGioHienTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 570, 160, 60));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Tên");
        lblName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 140, 50));

        lblAnh.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh.setText("Ảnh người dùng");
        lblAnh.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(51, 51, 51)));
        jPanel2.add(lblAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 350));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 170, 230, 350));

        lblBackRound.setIcon(new javax.swing.ImageIcon("C:\\Users\\NITRO 5\\Documents\\NetBeansProjects\\NET-MANAGERTest\\NET-MANAGER-main\\src\\main\\java\\img\\BackRoundNetManager.png")); // NOI18N
        lblBackRound.setOpaque(true);
        lblBackRound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackRoundMouseEntered(evt);
            }
        });
        getContentPane().add(lblBackRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 1530, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoMayActionPerformed
        this.showMoMay(this);
        CapNhat();
    }//GEN-LAST:event_btnMoMayActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        dangXuat();
        CapNhat();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        NgayHienTai();
    }//GEN-LAST:event_formWindowOpened

    private void menuHeThongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHeThongMouseEntered
        CapNhat();
    }//GEN-LAST:event_menuHeThongMouseEntered

    private void btnTrandPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrandPassActionPerformed
        new DoiMatKhauJDialog(null, true).setVisible(true);
        CapNhat();
    }//GEN-LAST:event_btnTrandPassActionPerformed

    private void lbclmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbclmenuActionPerformed
        btnclmenu();
        CapNhat();
    }//GEN-LAST:event_lbclmenuActionPerformed

    private void btnQLTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTKActionPerformed
        this.showQLThongke(this);
        CapNhat();
    }//GEN-LAST:event_btnQLTKActionPerformed

    private void btnQLMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLMTActionPerformed
        this.showQLmay(this);
        CapNhat();
    }//GEN-LAST:event_btnQLMTActionPerformed

    private void btnQLTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTDActionPerformed
        this.showQLOrder(this);
        CapNhat();
    }//GEN-LAST:event_btnQLTDActionPerformed

    private void btnQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNVActionPerformed
        this.showNhanVien(this);
        CapNhat();
    }//GEN-LAST:event_btnQLNVActionPerformed

    private void menuHeThongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHeThongMouseClicked
        btnopmenu();
        CapNhat();
    }//GEN-LAST:event_menuHeThongMouseClicked

    private void pnlMenuTopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuTopMouseReleased

    }//GEN-LAST:event_pnlMenuTopMouseReleased

    private void menuHeThongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHeThongMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHeThongMouseExited

    private void lblBackRoundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackRoundMouseEntered
        CapNhat();
    }//GEN-LAST:event_lblBackRoundMouseEntered

    private void pnlMenuTopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuTopMouseEntered
        CapNhat();
    }//GEN-LAST:event_pnlMenuTopMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Set FlatLaf (light theme)
            Style_Net.setup();
        } catch (Exception ex) {
            System.err.println("Không thể khởi tạo FlatLaf: " + ex.getMessage());
        }
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NetManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NetManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NetManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NetManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NetManagerJFrame().setVisible(true);
            }
        });
    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon myImage = new ImageIcon(ImagePath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), Image.SCALE_SMOOTH);
        return new ImageIcon(newImg);
    }

    public void setIconAll() {
        lblBackRound.setIcon(new ImageIcon("src/main/java/img/BackRoundNetManager.png"));
        lblSoMayTrong.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icon-computer32x32.png"));
        lblSoMayHoatDong.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icon-computer32x32.png"));
        btnMoMay.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icon-Open32x32.png"));
        btnTrandPass.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icon-pass32x32.png"));
        btnLogOut.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icon-Out32x32.png"));
        btnQLNV.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icon-manager.png"));
        btnQLMT.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icocn-computer.png"));
        btnQLTD.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icon-food.png"));
        btnQLTK.setIcon(new ImageIcon("src/main/java/img/Ui-manager-icocn-thongKe.png"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMoMay;
    private javax.swing.JButton btnQLMT;
    private javax.swing.JButton btnQLNV;
    private javax.swing.JButton btnQLTD;
    private javax.swing.JButton btnQLTK;
    private javax.swing.JButton btnTrandPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton lbclmenu;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblBackRound;
    private javax.swing.JLabel lblGioHienTai;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNgayHienTai;
    private javax.swing.JLabel lblSoMayHoatDong;
    private javax.swing.JLabel lblSoMayTrong;
    private javax.swing.JPanel menuHeThong;
    private javax.swing.JPanel pnlMenuTop;
    // End of variables declaration//GEN-END:variables

    @Override
    public void init() {
        this.showWelcome(this);
        this.showLogin(this);
        CapNhat();
        if (XAuth.user != null) {
            setRole();
        } else {
            dispose();
        }
        startDongHo();
    }

    private void loadAnhChinh(Admin admin) {
        if (admin.getAnh() != null && !admin.getAnh().isEmpty()) {
            String path = admin.getAnh();
            File f = new File(path);

            if (!f.exists()) {
                String alt = "src/images/" + path;
                if (new File(alt).exists()) {
                    path = alt;
                }
            }

            lblAnh.setIcon(ResizeImage(path));
        } else {
            lblAnh.setIcon(null);
        }
    }

    public void setRole() {
        int role = XAuth.user.getVaiTro();
        String name = XAuth.user.getTen();
        if (role == 2) { // Nhân viên
            menuHeThong.setVisible(false);
            btnQLNV.setEnabled(false);
            btnQLMT.setEnabled(false);
            btnQLTD.setEnabled(false);
            btnQLTK.setEnabled(false);
        } else {
            menuHeThong.setVisible(true);
            btnQLNV.setEnabled(true);
            btnQLMT.setEnabled(true);
            btnQLTD.setEnabled(true);
            btnQLTK.setEnabled(true);
        }
        Admin user = XAuth.user;
        loadAnhChinh(user);
        lblName.setText("<html>"
                + "<div style='text-align:center;'>"
                + "<span style='color: #0D47A1; font-size: 12px;'>Người sử dụng</span><br>"
                + "<span style='color: white; font-size: 16px; font-weight: bold;'>" + name + "</span>"
                + "</div>"
                + "</html>");
    }

    private void dangXuat() {
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn đăng xuất?", "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            XAuth.clear();
            this.setVisible(false);
            DangNhapJDialog dangNhap = new DangNhapJDialog(this, true);
            dangNhap.setVisible(true);
            if (XAuth.isLogin()) {
                this.setVisible(true);
                setRole();
            } else {
                dispose();
            }
        }
    }

    public void NgayHienTai() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String ngayHienTai = sdf.format(new Date());
        lblNgayHienTai.setText(ngayHienTai);
    }

    public void soMayHD() {
        int soMayHD = dao.getSoMayDangHoatDong();
        lblSoMayHoatDong.setText("<html>"
                + "<span style='color: #00E676; font-size: 14px;'>Số máy đang hoạt động:</span> "
                + "<span style='color: yellow; font-size: 18px; font-weight: bold;'>" + soMayHD + "</span>"
                + "</html>");

    }

    public void soMayT() {
        int soMayTrong = dao.getSoMayDangTrong();
        lblSoMayTrong.setText("<html>"
                + "<span style='color: #FF1744; font-size: 14px;'>Số máy trống:</span> "
                + "<span style='color: white; font-size: 18px; font-weight: bold;'>" + soMayTrong + "</span>"
                + "</html>");

    }

    public void CapNhat() {
        soMayHD();
        soMayT();
        setIconAll();
        pnlMenuTop.getParent().repaint();
        menuHeThong.getParent().repaint();
    }

    private void startDongHo() {
        dongHoTimer = new Timer(1000, e -> {
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm a");
            lblGioHienTai.setText(sdf.format(new Date()));
        });
        dongHoTimer.start();
    }

}
