/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.manager;

import daoImpl.MonAnDAOImpl;
import entity.MonAn;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import daoImpl.MenuDAOImpl;
import entity.Menu;
import dao.MenuDAO;
import dao.MonAnDAO;
import java.sql.Date;
import java.text.SimpleDateFormat;
import controller.MenuController;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import util.XDialog;

/**
 *
 * @author Admin
 */
public class MenuJDialog extends javax.swing.JDialog implements MenuController {

    /**
     * Creates new form MenuJDialog
     */
    private MonAnDAO MonAnDao = new MonAnDAOImpl();
    private MenuDAO MenuDao = new MenuDAOImpl();

    public MenuJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);

    public MenuJDialog(java.awt.Frame parent, boolean modal, String maMay, String TenMay) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        fillToTable();
        scheduler.schedule(() -> {
            filltblDaNMua();
        }, 1, TimeUnit.SECONDS);
        scheduler.shutdown();
        lblTenMay.setText(TenMay);
        lblMaSd.setText(maMay);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderManager = new javax.swing.JTable();
        lblTenMay = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_mua = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();
        lblMaSd = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        lblMaDaMua = new javax.swing.JLabel();
        lblGiaMon = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblNgayHienTai = new javax.swing.JLabel();
        Tabpnl = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTongMonAn = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDaMua = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Thực Đơn");

        tblOrderManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã đồ món", "Tên món", "Đơn Giá"
            }
        ));
        jScrollPane2.setViewportView(tblOrderManager);

        lblTenMay.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTenMay.setText("Tên máy");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Tổng");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_mua.setText("Mua");
        btn_mua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_muaActionPerformed(evt);
            }
        });

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_Clear.setText("Làm mới");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        btn_huy.setText("Hủy mua");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        lblMaSd.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        lblMaSd.setForeground(new java.awt.Color(255, 255, 255));

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        lblMaDaMua.setForeground(new java.awt.Color(255, 255, 255));

        lblGiaMon.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_mua, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSua)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMaDaMua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMaSd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGiaMon)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSua, btn_them});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mua)
                    .addComponent(btn_Clear))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_huy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMaDaMua, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                            .addComponent(lblMaSd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblGiaMon)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSua, btn_them});

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        lblNgayHienTai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tblTongMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã món", "Tên món", "Giá", "Số Lượng"
            }
        ));
        tblTongMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTongMonAnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTongMonAn);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        Tabpnl.addTab("Danh sách đang mua", jPanel2);

        tblDaMua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã đã mua", "Tên món", "Giá món", "Số lượng", "Tổng tiền"
            }
        ));
        tblDaMua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDaMuaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDaMua);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );

        Tabpnl.addTab("Danh sách đã mua", jPanel3);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Số lượng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNgayHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(Tabpnl))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblTenMay, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtSoLuong, txtTongTien});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblNgayHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Tabpnl, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblTenMay, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel5});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtSoLuong, txtTongTien});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        int selectedRow = tblTongMonAn.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) tblTongMonAn.getModel();
            model.removeRow(selectedRow);
            updateTongTien();
            JOptionPane.showMessageDialog(this, "Đã hủy món thành công.");
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần hủy.");
        }


    }//GEN-LAST:event_btn_huyActionPerformed

    private void btn_muaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_muaActionPerformed
        this.create();
    }//GEN-LAST:event_btn_muaActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        int selectedRow = tblOrderManager.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn món trong bảng OrderManager.");
            return;
        }

        String ma = tblOrderManager.getValueAt(selectedRow, 0).toString();
        String ten = tblOrderManager.getValueAt(selectedRow, 1).toString();
        float gia = Float.parseFloat(tblOrderManager.getValueAt(selectedRow, 2).toString());

        DefaultTableModel model = (DefaultTableModel) tblTongMonAn.getModel();
        boolean found = false;

        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).toString().equals(ma)) {
                int currentQty = Integer.parseInt(model.getValueAt(i, 3).toString());
                model.setValueAt(currentQty + 1, i, 3);  // tăng số lượng
                found = true;
                break;
            }
        }

        if (!found) {
            model.addRow(new Object[]{ma, ten, gia, 1});  // thêm mới với số lượng = 1
        }

        updateTongTien(); // cập nhật tổng tiền sau khi thêm
    }//GEN-LAST:event_btn_themActionPerformed

    private void tblTongMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTongMonAnMouseClicked
        int row = tblTongMonAn.getSelectedRow();
        if (row < 0) {
            return;
        }

        String tongTien = tblTongMonAn.getValueAt(row, 2).toString();
        String soLuong = tblTongMonAn.getValueAt(row, 3).toString();

        txtSoLuong.setText(soLuong);
        txtTongTien.setText(tongTien);

    }//GEN-LAST:event_tblTongMonAnMouseClicked

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        this.clear();
        filltblDaNMua();
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        NgayHienTai();
    }//GEN-LAST:event_formWindowOpened

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed

    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (tblOrderManager.getSelectedRow() != 0) {
            XDialog.alert("Sua thanh cong");
            SuaSoLuong();
            return;
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblDaMuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDaMuaMouseClicked
        int Slt = tblDaMua.getSelectedRow();
        if (Slt >= 0) {
            String id = tblDaMua.getValueAt(Slt, 0).toString();
            String GiaTien = tblDaMua.getValueAt(Slt, 2).toString();
            String Soluong = tblDaMua.getValueAt(Slt, 3).toString();
            String Tong = tblDaMua.getValueAt(Slt, 4).toString();
            txtSoLuong.setText(Soluong);
            txtTongTien.setText(Tong);
            lblMaDaMua.setText(id);
            lblGiaMon.setText(GiaTien);
        }
    }//GEN-LAST:event_tblDaMuaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuJDialog dialog = new MenuJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabpnl;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_mua;
    private javax.swing.JButton btn_them;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblGiaMon;
    private javax.swing.JLabel lblMaDaMua;
    private javax.swing.JLabel lblMaSd;
    private javax.swing.JLabel lblNgayHienTai;
    private javax.swing.JLabel lblTenMay;
    private javax.swing.JTable tblDaMua;
    private javax.swing.JTable tblOrderManager;
    private javax.swing.JTable tblTongMonAn;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    private void updateTongTien() {
        DefaultTableModel model = (DefaultTableModel) tblTongMonAn.getModel();
        double tongTien = 0;

        for (int i = 0; i < model.getRowCount(); i++) {
            Object giaObj = model.getValueAt(i, 2);
            Object soLuongObj = model.getValueAt(i, 3);

            if (giaObj != null && soLuongObj != null) {
                float gia = Float.parseFloat(giaObj.toString());
                int soLuong = Integer.parseInt(soLuongObj.toString());
                tongTien += gia * soLuong;
            }
        }
        txtTongTien.setText(String.valueOf(tongTien));
    }

    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrderManager.getModel();
        model.setRowCount(0);
        List<MonAn> items = MonAnDao.findAll();
        for (MonAn item : items) {
            Object[] rowData = {
                item.getId(),
                item.getTenMon(),
                item.getGiaTien()
            };
            model.addRow(rowData);
        }
    }

    public void create() {
        int MaSD = Integer.parseInt(lblMaSd.getText().trim());
        String tenMay = lblTenMay.getText().trim();
        String tongTienStr = txtTongTien.getText().trim();

        try {
            float tongTien = Float.parseFloat(tongTienStr);

            DefaultTableModel model = (DefaultTableModel) tblTongMonAn.getModel();
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Không có món nào để mua.");
                return;
            }

            // Giả sử ngayMua là dạng "yyyy-MM-dd"
            java.sql.Date ngayMua = new java.sql.Date(System.currentTimeMillis());

            for (int i = 0; i < model.getRowCount(); i++) {
                String maMon = model.getValueAt(i, 0).toString();
                String tenMon = model.getValueAt(i, 1).toString();
                float gia = Float.parseFloat(model.getValueAt(i, 2).toString());
                int soLuong = Integer.parseInt(model.getValueAt(i, 3).toString());

                // ✅ Tính tổng tiền của từng món
                double tongTienMon = gia * soLuong;

                Menu order = new Menu(i, MaSD, tenMay, maMon, tenMon, gia, ngayMua, soLuong, tongTienMon);
                MenuDao.Mua(order);
            }

            XDialog.alert("Mua thành công");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi mua: " + e.getMessage());
        }
    }

    public void clear() {
        txtTongTien.setText("");
        txtSoLuong.setText("");
        DefaultTableModel model = (DefaultTableModel) tblTongMonAn.getModel();
        model.setRowCount(0);
    }

    public void NgayHienTai() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        lblNgayHienTai.setText("Ngày hiện tại " + sdf.format(new java.util.Date()));
    }

    @Override
    public void filltblDaNMua() {
        DefaultTableModel model = (DefaultTableModel) tblDaMua.getModel();
        model.setRowCount(0);
        int MaSDMay = Integer.parseInt(lblMaSd.getText());
        List<Menu> items = MenuDao.FindByIdSD(MaSDMay);
        for (Menu item : items) {
            Object[] rowData = {
                item.getId(),
                item.getTenMon(),
                item.getGiaTien(),
                item.getSoLuong(),
                item.getTongTien()
            };
            model.addRow(rowData);
        }
    }

    @Override
    public Menu getFromDaMua() {
        Menu mn = new Menu();

        String idText = lblMaDaMua.getText().trim();
        String tongTienText = txtTongTien.getText().trim();
        String soLuongText = txtSoLuong.getText().trim();

        if (idText.isEmpty() || tongTienText.isEmpty() || soLuongText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn món từ bảng đã mua trước khi sửa.");
            return null; // hoặc throw exception
        }

        mn.setId(Integer.parseInt(idText));
        mn.setTongTien(Double.parseDouble(tongTienText));
        mn.setSoLuong(Integer.parseInt(soLuongText));

        return mn;
    }

    @Override
    public void SuaSoLuong() {
        Menu mn = this.getFromDaMua();
        MenuDao.UpSoluong(mn);
        filltblDaNMua();
    }

}
