/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.manager;

import controller.MoMayController;
import dao.MayTinhDAO;
import daoImpl.MayTinhDAOImpl;
import entity.MayTinh;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import util.XDialog;

/**
 *
 * @author VINH
 */
public class MoMayJDialog extends javax.swing.JDialog implements MoMayController {

    MayTinhDAO dao = new MayTinhDAOImpl();
    List<MayTinh> list = new ArrayList<>();

    /**
     * Creates new form MoMayJDialog
     */
    public MoMayJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        txtViTri = new javax.swing.JTextField();
        txtThoiGian = new javax.swing.JTextField();
        btnTatMay = new javax.swing.JButton();
        btnMoMay = new javax.swing.JButton();
        btnBaoTri = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        rdoHoatDong = new javax.swing.JRadioButton();
        rdoNgungHoatDong = new javax.swing.JRadioButton();
        rdoBaoTri = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaMay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTenMay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtViTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViTriActionPerformed(evt);
            }
        });

        btnTatMay.setText("Tắt máy");
        btnTatMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTatMayActionPerformed(evt);
            }
        });

        btnMoMay.setText("Mở máy");
        btnMoMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoMayActionPerformed(evt);
            }
        });

        btnBaoTri.setText("Bảo trì");
        btnBaoTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaoTriActionPerformed(evt);
            }
        });

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã máy", "Tên máy", "Trạng thái", "Vị trí", "Thời gian"
            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);

        buttonGroup1.add(rdoHoatDong);
        rdoHoatDong.setText("Đang hoạt động");

        buttonGroup1.add(rdoNgungHoatDong);
        rdoNgungHoatDong.setText("Ngừng hoạt động");

        buttonGroup1.add(rdoBaoTri);
        rdoBaoTri.setText("Bảo trì");

        jLabel9.setText("Vị trí");

        jLabel10.setText("Thời gian");

        jLabel6.setText("Mã máy");

        jLabel7.setText("Tên máy");

        jLabel8.setText("Trạng thái");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Mở máy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoNgungHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenMay, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaMay, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoBaoTri, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViTri, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMoMay, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTatMay, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBaoTri))
                    .addComponent(txtThoiGian))
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoHoatDong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoNgungHoatDong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoBaoTri)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMoMay)
                        .addComponent(btnTatMay)
                        .addComponent(btnBaoTri)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.open();
    }//GEN-LAST:event_formWindowOpened

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseClicked

    private void btnBaoTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaoTriActionPerformed
        // TODO add your handling code here:
        this.BaoTri();
    }//GEN-LAST:event_btnBaoTriActionPerformed

    private void btnTatMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTatMayActionPerformed
        // TODO add your handling code here:
        this.TatMay();
    }//GEN-LAST:event_btnTatMayActionPerformed

    private void btnMoMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoMayActionPerformed
        // TODO add your handling code here:
        this.MoMay();
    }//GEN-LAST:event_btnMoMayActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        // TODO add your handling code here:
        int row = tblDanhSach.getSelectedRow();
        if (row >= 0) {
            setText(row);
        }
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void txtViTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViTriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoMayJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoMayJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoMayJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoMayJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MoMayJDialog dialog = new MoMayJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaoTri;
    private javax.swing.JButton btnMoMay;
    private javax.swing.JButton btnTatMay;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rdoBaoTri;
    private javax.swing.JRadioButton rdoHoatDong;
    private javax.swing.JRadioButton rdoNgungHoatDong;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtMaMay;
    private javax.swing.JTextField txtTenMay;
    private javax.swing.JTextField txtThoiGian;
    private javax.swing.JTextField txtViTri;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
        this.setLocationRelativeTo(null);
        this.fillToTable();
        this.clear();
    }

    @Override
    public void setForm(MayTinh entity) {
        txtMaMay.setText(entity.getMaMayTinh());
        txtTenMay.setText(entity.getTenMay());
        txtViTri.setText(entity.getViTri());
        txtThoiGian.setText(String.valueOf(entity.getThoiGian()));
        buttonGroup1.clearSelection();

        String trangThaistr = entity.getTrangThai();
        if (trangThaistr.equals(ABORT)) {

        }
    }

    @Override
    public MayTinh getForm() {
        MayTinh entity = new MayTinh();

        String maMay = txtMaMay.getText().trim(); // trim dùng để xóa khoảng trắng đầu cuối
        if (maMay.isEmpty()) {
            XDialog.alert("Mã máy không được để trống!");
            return null;
        }

        String tenMay = txtTenMay.getText().trim();
        if (tenMay.isEmpty()) {
            XDialog.alert("Tên máy không được để trống!");
            return null;
        }

        String viTri = txtViTri.getText().trim();
        if (viTri.isEmpty()) {
            XDialog.alert("Vị trí không được để trống!");
            return null;
        }

        String trangThai;
        if (rdoHoatDong.isSelected()) {
            trangThai = "Đang hoạt động";
        } else if (rdoNgungHoatDong.isSelected()) {
            trangThai = "Ngừng hoạt động";
        } else if (rdoBaoTri.isSelected()) {
            trangThai = "Bảo trì";
        } else {
            XDialog.alert("Vui lòng chọn trạng thái!");
            return null;
        }
        String strThoiGian = txtThoiGian.getText().trim();
        if (strThoiGian.isEmpty()) {
            XDialog.alert("Thoi gian khong duoc rong");
        }

        int thoiGian;
        try {
            thoiGian = Integer.parseInt(strThoiGian);
            if (thoiGian < 0) {
                XDialog.alert("Thoi gian khong duoc am");
                return null;
            }
        } catch (Exception e) {
            XDialog.alert("Thoi gian phai la so nguyen");
            e.printStackTrace();
            return null;
        }

        if (trangThai.equals("Ngừng hoạt động") || trangThai.equals("Bảo trì")) {
            thoiGian = 0;
            txtThoiGian.setText("0");
        }
        /**
         * xét trạng thái ngừng hoạt động và bảo trì thì đưa thời gian về 0
         */

        // Gán các giá trị vào entity
        entity.setMaMayTinh(maMay);
        entity.setTenMay(tenMay);
        entity.setViTri(viTri);
        entity.setTrangThai(trangThai);
        entity.setThoiGian(thoiGian);

        return entity;
    }

    @Override
    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSach.getModel();
        model.setRowCount(0);
        list = dao.findAll();
        list.forEach(item -> {
            Object[] rowData = {
                item.getMaMayTinh(),
                item.getTenMay(),
                item.getTrangThai(),
                item.getViTri(),
                item.getThoiGian()
            };
            model.addRow(rowData);
        });
    }

    @Override
    public void create() {
        MayTinh entity = this.getForm();
        if (entity == null) {
            return; // Không tạo nếu getForm trả về null
        }
        try {
            dao.create(entity);
            this.fillToTable();
            this.clear();
            XDialog.alert("Thêm máy thành công!");
        } catch (Exception e) {
            XDialog.alert("Lỗi: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void setText(int row) {
        String ma = tblDanhSach.getValueAt(row, 0).toString();
        String ten = tblDanhSach.getValueAt(row, 1).toString();
        String trangThai = tblDanhSach.getValueAt(row, 2).toString();
        String viTri = tblDanhSach.getValueAt(row, 3).toString();
        String thoiGian = tblDanhSach.getValueAt(row, 4).toString();

        txtMaMay.setText(ma);
        txtTenMay.setText(ten);
        txtThoiGian.setText(thoiGian);
        txtViTri.setText(viTri);

        rdoHoatDong.setSelected(false);
        rdoNgungHoatDong.setSelected(false);
        rdoBaoTri.setSelected(true);

        if (trangThai.equals("Đang hoạt động")) {
            rdoHoatDong.setSelected(true);
        } else if (trangThai.equals("Ngừng hoạt động")) {
            rdoNgungHoatDong.setSelected(true);
        } else {
            rdoBaoTri.setSelected(true);
        }
    }

    private void MoMay() {
        int row = tblDanhSach.getSelectedRow();
        if (row < 0) {
            XDialog.alert("Chọn máy mà bạn muốn mở");
            return;
        }

        String trangthai = tblDanhSach.getValueAt(row, 2).toString();
        /**
         * row, 2 là vì trạng thái trong bảng đang là cột thứ 3 và bắt đầu từ số
         * 0
         */
        if (trangthai.equals("Đang hoạt động")) {
            XDialog.alert("Máy đang hoạt động, vui lòng mở máy khác");
            return;
        }
        /*
        Nếu trạng thái hiện tại là bảo trì hoặc ngừng hoạt động thì yêu cầu nhập lại thời gian
         */
        String strThoiGian = txtThoiGian.getText().trim();
        int thoiGian = 0;
        if (trangthai.equals("Bảo trì") || trangthai.equals("Ngừng hoạt động")) {
            if (strThoiGian.isEmpty()) {
                XDialog.alert("Vui lòng nhập lại thời gian sử dụng khi mở lại máy sau bảo trì!");
                return;
            }

            try {
                thoiGian = Integer.parseInt(strThoiGian); // kiểm tra thời gian người dùng nhập
                if (thoiGian <= 0) {
                    XDialog.alert("Thời gian phải lớn hơn 0!");
                    return;
                }
            } catch (NumberFormatException e) {
                XDialog.alert("Thời gian phải là số nguyên!");
                return;
            }
        }
        /**
         * kiểm tra thời gian nếu = 0 thì phải nhập
         */

        MayTinh mt = getForm(); // lấy thông tin máy từ form
        /*
        lấy dữ liệu từ form
         */
        if (mt == null) {
            return;
        }
        /**
         * Nếu form bị lỗi khi nhập thì sẽ ngừng và không thực hiện tiếp
         */

        mt.setTrangThai("Đang hoạt động"); // cập nhật trạng thái sang "Đang hoạt động"
        mt.setThoiGian(thoiGian); // cập nhật lại thời gian (bạn đang bị thiếu dòng này)

        try {
            dao.update(mt); // cập nhật vào database
            fillToTable();  // đổ lại bảng
            clear();        // xóa form
            XDialog.alert("Mở máy thành công");
        } catch (Exception e) {
            e.printStackTrace();
            XDialog.alert("Lỗi mở máy" + e.getMessage());
        }
    }

    private void TatMay() {
        int row = tblDanhSach.getSelectedRow();
        if (row < 0) {
            XDialog.alert("Chọn máy bạn muốn tăt!");
            return;
        }

        String trangthai = tblDanhSach.getValueAt(row, 2).toString();
        if (trangthai.equals("Ngừng hoạt động")) {
            XDialog.alert("Máy đã tắt!");
            return;
        }

        MayTinh entity = getForm();
        if (entity == null) {
            return;
        }

        entity.setTrangThai("Ngừng hoạt động");

        try {
            dao.update(entity);
            fillToTable();
            clear();
            XDialog.alert("Tắt máy thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            XDialog.alert("Lỗi tắt máy: " + e.getMessage());
        }
    }

    private void BaoTri() {
        int row = tblDanhSach.getSelectedRow();
        if (row < 0) {
            XDialog.alert("Chọn máy bạn muốn bảo trì!");
            return;
        }

        String trangthai = tblDanhSach.getValueAt(row, 2).toString();
        if (trangthai.equals("Bảo trì")) {
            XDialog.alert("Máy đang bảo trì!");
            return;
        }

        MayTinh entity = getForm();
        if (entity == null) {
            return;
        }

        entity.setTrangThai("Bảo trì");

        try {
            dao.update(entity);
            fillToTable();
            clear();
            XDialog.alert("Đưa vào bảo trì thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            XDialog.alert("Lỗi bảo trì máy: " + e.getMessage());
        }
    }

    @Override
    public void update() {
        MayTinh mt = this.getForm();
        if (mt == null) {
            return; // Nếu form không hợp lệ (ví dụ thiếu dữ liệu), không cập nhật
        }

        try {
            dao.update(mt); // Gửi đối tượng máy đã chỉnh sửa lên DB
            this.fillToTable(); // Làm mới bảng
            this.clear();
            XDialog.alert("Cập nhật thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            XDialog.alert("Cập nhật thất bại: " + e.getMessage());
        }
    }

// khong dung den
    @Override
    public void edit() {

    }

    @Override
    public void delete() {
    }

    @Override
    public void clear() {
    }

    @Override
    public void setEditable(boolean editable) {
    }

    @Override
    public void close() {

    }
}
