/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.manager;

import controller.QuanLyThongKeController;
import daoImpl.QuanLyThongKeDaoImpl;
import entity.Menu;
import entity.SuDungMay;
import entity.ThongKeDoanhThu;
import java.sql.Date;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import dao.QuanLyThongKeDAO;
import util.XDialog;

// Import model & controller
/**
 *
 * @author Admin
 */
public class QuanLyThongKeJDialog extends javax.swing.JDialog implements QuanLyThongKeController {

    /**
     * Creates new form QuanLyThongKeJDialog
     */
    QuanLyThongKeDAO dao = new QuanLyThongKeDaoImpl();
    DefaultTableModel model;

    public QuanLyThongKeJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        getFillSDMay();
        getFillMenu();
        getFillThonKe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnXemSuDungMay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuDungMay = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTongGio = new javax.swing.JTextField();
        jdcTuNgay = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        dacDenNgayMay = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMonAn = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnMonAn = new javax.swing.JButton();
        jdcMonAn = new com.toedter.calendar.JDateChooser();
        txtTongMonAn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dacDenNgayMenu = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnXemBangThongke = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDoanhThu = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtTongDoanhThu = new javax.swing.JTextField();
        dacTuNgayThongKe = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        dacDenNgayThongKe = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Thống Kê");

        jLabel2.setText("Từ ngày");

        btnXemSuDungMay.setText("Xem");
        btnXemSuDungMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemSuDungMayActionPerformed(evt);
            }
        });

        tblSuDungMay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên máy", "Số lần sử dụng", "Tổng TG sử dụng", "Giá/h", "Tổng tiền"
            }
        ));
        tblSuDungMay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuDungMayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSuDungMay);

        jLabel6.setText("Tổng tiền tất cả máy");

        jLabel7.setText("Tổng giờ sử dụng");

        jLabel4.setText("Đến ngày");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdcTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dacDenNgayMay, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTongGio, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addComponent(btnXemSuDungMay, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 45, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(txtTongGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnXemSuDungMay))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dacDenNgayMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lịch Sử Sử Dụng Máy ", jPanel1);

        tblMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã món", "Tên món", "Tổng số lượng bán", "Tổng tiền món"
            }
        ));
        tblMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMonAnMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMonAn);

        jLabel11.setText("Từ ngày");

        btnMonAn.setText("Xem");
        btnMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonAnActionPerformed(evt);
            }
        });

        jLabel3.setText("Tổng doanh thu");

        jLabel5.setText("Đến ngày");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(dacDenNgayMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtTongMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(btnMonAn))))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dacDenNgayMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTongMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMonAn))))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Lịch Sử Bán Hàng", jPanel3);

        jLabel8.setText("Từ ngày ");

        btnXemBangThongke.setText("Xem");
        btnXemBangThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemBangThongkeActionPerformed(evt);
            }
        });

        tblDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tổng tiền món", "Tổng tiền máy"
            }
        ));
        tblDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDoanhThuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDoanhThu);

        jLabel10.setText("Tổng doanh thu");

        jLabel9.setText("Đến ngày");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dacTuNgayThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dacDenNgayThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(btnXemBangThongke)
                        .addGap(50, 50, 50))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXemBangThongke)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dacTuNgayThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dacDenNgayThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Doanh Thu", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemBangThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemBangThongkeActionPerformed
        if (tblSuDungMay.getSelectedRow() == 0) {
            thongKeDoanhThu();
            return;
        }
    }//GEN-LAST:event_btnXemBangThongkeActionPerformed

    private void btnXemSuDungMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemSuDungMayActionPerformed
        if (tblMonAn.getSelectedRow() == 0) {
            thongKeSuDungMay();
            return;
        }
    }//GEN-LAST:event_btnXemSuDungMayActionPerformed

    private void btnMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonAnActionPerformed
        if (tblDoanhThu.getSelectedRow() == 0) {
            thongKeLichSuBanHang();
            return;
        }
    }//GEN-LAST:event_btnMonAnActionPerformed

    private void tblSuDungMayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuDungMayMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblSuDungMay.getSelectedRow();
        if (selectedRow >= 0) {
            // Lấy giá trị từ dòng được chọn
            String tongTienStr = tblSuDungMay.getValueAt(selectedRow, 4).toString();
            String tongGioStr = tblSuDungMay.getValueAt(selectedRow, 2).toString();
            txtTongTien.setText(tongTienStr);
            txtTongGio.setText(tongGioStr + " giờ");
        } else {
            // Nếu không có dòng nào được chọn, hiển thị tổng tất cả
            getFillSDMay();
        }
    }//GEN-LAST:event_tblSuDungMayMouseClicked

    private void tblMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMonAnMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblMonAn.getSelectedRow();
        if (selectedRow >= 0) {
            // Lấy giá trị từ dòng được chọn
            String tongTienMonStr = tblMonAn.getValueAt(selectedRow, 3).toString();
            txtTongMonAn.setText(tongTienMonStr);
        } else {
            // Nếu không có dòng nào được chọn, hiển thị tổng tất cả
            getFillMenu();
        }
    }//GEN-LAST:event_tblMonAnMouseClicked

    private void tblDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDoanhThuMouseClicked
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("#,### VND");
        int selectedRow = tblDoanhThu.getSelectedRow();
        if (selectedRow >= 0) {
            // Lấy giá trị từ dòng được chọn
            String tongTienMayStr = tblDoanhThu.getValueAt(selectedRow, 0).toString();
            String tongTienMonStr = tblDoanhThu.getValueAt(selectedRow, 1).toString();
            double tongDoanhThu = 0;
            try {
                // Loại bỏ định dạng để tính tổng
                String tongTienMayClean = tongTienMayStr.replace(" VND", "").replace(",", "");
                String tongTienMonClean = tongTienMonStr.replace(" VND", "").replace(",", "");
                tongDoanhThu = Double.parseDouble(tongTienMayClean) + Double.parseDouble(tongTienMonClean);
            } catch (NumberFormatException ex) {
                ex.printStackTrace();
            }
            txtTongDoanhThu.setText(df.format(tongDoanhThu));
        } else {
            // Nếu không có dòng nào được chọn, hiển thị tổng tất cả
            getFillThonKe();
        }
    }//GEN-LAST:event_tblDoanhThuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyThongKeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyThongKeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyThongKeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyThongKeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyThongKeJDialog dialog = new QuanLyThongKeJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMonAn;
    private javax.swing.JButton btnXemBangThongke;
    private javax.swing.JButton btnXemSuDungMay;
    private com.toedter.calendar.JDateChooser dacDenNgayMay;
    private com.toedter.calendar.JDateChooser dacDenNgayMenu;
    private com.toedter.calendar.JDateChooser dacDenNgayThongKe;
    private com.toedter.calendar.JDateChooser dacTuNgayThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdcMonAn;
    private com.toedter.calendar.JDateChooser jdcTuNgay;
    private javax.swing.JTable tblDoanhThu;
    private javax.swing.JTable tblMonAn;
    private javax.swing.JTable tblSuDungMay;
    private javax.swing.JTextField txtTongDoanhThu;
    private javax.swing.JTextField txtTongGio;
    private javax.swing.JTextField txtTongMonAn;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
@Override
    public List<ThongKeDoanhThu> getFillThonKe() {
        List<ThongKeDoanhThu> list = dao.getAllThonKe();
        model = (DefaultTableModel) tblDoanhThu.getModel();
        model.setRowCount(0);

        DecimalFormat df = new DecimalFormat("#,### VND");
        double tongDoanhThu = 0;

        for (ThongKeDoanhThu tkd : list) {
            double tongTienMay = tkd.getTongTienMay();
            double tongTienMon = tkd.getTongTienMon();
            model.addRow(new Object[]{
                df.format(tongTienMay),
                df.format(tongTienMon)
            });
            tongDoanhThu += tongTienMay + tongTienMon;
        }
        txtTongDoanhThu.setText(df.format(tongDoanhThu));
        return list;
    }

    @Override
    public List<SuDungMay> getFillSDMay() {
        List<SuDungMay> entity = dao.getAllSDMay();
        model = (DefaultTableModel) tblSuDungMay.getModel();
        model.setRowCount(0);

        DecimalFormat df = new DecimalFormat("#,### VND");
        double tongTienTatCa = 0;
        float tongGio = 0;

        for (SuDungMay item : entity) {
            double tongTienMay = item.getThoiGianChoi() * item.getGiaTheoGio();
            model.addRow(new Object[]{
                item.getTenMay(),
                item.getMaMay(),
                String.format("%.2f", item.getThoiGianChoi()),
                df.format(item.getGiaTheoGio()),
                df.format(tongTienMay)
            });
            tongTienTatCa += tongTienMay;
            tongGio += item.getThoiGianChoi();
        }
        txtTongTien.setText(df.format(tongTienTatCa));
        txtTongGio.setText(String.format("%.2f giờ", tongGio));
        return entity;
    }

    @Override
    public List<Menu> getFillMenu() {
        List<Menu> entityMenu = dao.getAllMenu();
        model = (DefaultTableModel) tblMonAn.getModel();
        model.setRowCount(0);

        DecimalFormat df = new DecimalFormat("#,### VND");
        double tongMonAn = 0;

        for (Menu item : entityMenu) {
            double tongTienMon = item.getTongTien();
            model.addRow(new Object[]{
                item.getMaMon(),
                item.getTenMon(),
                item.getSoLuong(),
                df.format(tongTienMon)
            });
            tongMonAn += tongTienMon;
        }
        txtTongMonAn.setText(df.format(tongMonAn));
        return entityMenu;
    }

    private void thongKeSuDungMay() {
        if (jdcTuNgay.getDate() == null || dacDenNgayMay.getDate() == null) {
            XDialog.alert("Vui lòng chọn đầy đủ ngày bắt đầu và ngày kết thúc");
            return;
        }

        Date tuNgay = new Date(jdcTuNgay.getDate().getTime());
        Date denNgay = new Date(dacDenNgayMay.getDate().getTime());
        DecimalFormat df = new DecimalFormat("#,### VND");
        QuanLyThongKeDaoImpl dao = new QuanLyThongKeDaoImpl();

        // Lịch sử sử dụng máy
        List<SuDungMay> lsMay = dao.getLichSuSuDungMay(tuNgay, denNgay);
        DefaultTableModel modelMay = (DefaultTableModel) tblSuDungMay.getModel();
        modelMay.setRowCount(0);
        double tongTienMay = 0;
        float tongGioSuDung = 0;
        for (SuDungMay sdm : lsMay) {
            double tienMay = sdm.getThoiGianChoi() * sdm.getGiaTheoGio();
            modelMay.addRow(new Object[]{
                sdm.getTenMay(),
                sdm.getMaMay(),
                String.format("%.2f", sdm.getThoiGianChoi()),
                df.format(sdm.getGiaTheoGio()),
                df.format(tienMay)
            });
            tongTienMay += tienMay;
            tongGioSuDung += sdm.getThoiGianChoi();
        }
        txtTongTien.setText(df.format(tongTienMay));
        txtTongGio.setText(String.format("%.2f giờ", tongGioSuDung));
    }

    private void thongKeLichSuBanHang() {
        if (jdcMonAn.getDate() == null || dacDenNgayMenu.getDate() == null) {
            XDialog.alert("Vui lòng chọn đầy đủ ngày bắt đầu và ngày kết thúc");
            return;
        }

        Date tuNgay = new Date(jdcMonAn.getDate().getTime());
        Date denNgay = new Date(dacDenNgayMenu.getDate().getTime());
        DecimalFormat df = new DecimalFormat("#,### VND");
        QuanLyThongKeDaoImpl dao = new QuanLyThongKeDaoImpl();

        // Lịch sử Menu (món ăn)
        List<Menu> lsMenu = dao.getLichSuMenu(tuNgay, denNgay);
        DefaultTableModel modelMenu = (DefaultTableModel) tblMonAn.getModel();
        modelMenu.setRowCount(0);
        double tongMonAn = 0;
        for (Menu m : lsMenu) {
            modelMenu.addRow(new Object[]{
                m.getMaMon(),
                m.getTenMon(),
                m.getSoLuong(),
                df.format(m.getTongTien())
            });
            tongMonAn += m.getTongTien();
        }
        txtTongMonAn.setText(df.format(tongMonAn));
    }

    private void thongKeDoanhThu() {
        if (dacTuNgayThongKe.getDate() == null || dacDenNgayThongKe.getDate() == null) {
            XDialog.alert("Vui lòng chọn đầy đủ ngày bắt đầu và ngày kết thúc");
            return;
        }

        Date tuNgay = new Date(dacTuNgayThongKe.getDate().getTime());
        Date denNgay = new Date(dacDenNgayThongKe.getDate().getTime());
        DecimalFormat df = new DecimalFormat("#,### VND");
        QuanLyThongKeDaoImpl dao = new QuanLyThongKeDaoImpl();

        // Lịch sử sử dụng máy
        List<SuDungMay> lsMay = dao.getLichSuSuDungMay(tuNgay, denNgay);
        double tongTienMay = 0;
        for (SuDungMay sdm : lsMay) {
            double tienMay = sdm.getThoiGianChoi() * sdm.getGiaTheoGio();
            tongTienMay += tienMay;
        }

        // Lịch sử Menu (món ăn)
        List<Menu> lsMenu = dao.getLichSuMenu(tuNgay, denNgay);
        double tongMonAn = 0;
        for (Menu m : lsMenu) {
            tongMonAn += m.getTongTien();
        }

        // Cập nhật bảng doanh thu
        DefaultTableModel dtModel = (DefaultTableModel) tblDoanhThu.getModel();
        dtModel.setRowCount(0);
        dtModel.addRow(new Object[]{df.format(tongTienMay), df.format(tongMonAn)});

        // Cập nhật tổng doanh thu
        txtTongDoanhThu.setText(df.format(tongTienMay + tongMonAn));
    }
}
